//! 100 WANDS-style e-commerce search queries, varied across categories.

pub const QUERIES: &[&str] = &[
    // accent chairs / seating
    "comfy reading chair for small living room",
    "mid-century modern accent chair",
    "leather club chair with ottoman",
    "swivel barrel chair in cream",
    "tufted velvet wingback chair",
    "small armchair for bedroom corner",
    "rocking chair for nursery",
    "outdoor adirondack chair set",
    "ergonomic office chair with lumbar support",
    "bar stool with backrest counter height",
    // sofas
    "sectional sofa with chaise gray",
    "compact apartment sofa under 70 inches",
    "leather recliner sofa power motion",
    "modular cloud couch deep seat",
    "sleeper sofa twin queen size",
    // tables
    "round farmhouse dining table for 6",
    "live edge wood coffee table",
    "extendable dining table seats 10",
    "nesting side tables marble top",
    "console table with drawers entryway",
    "writing desk with hutch industrial",
    // beds / mattresses
    "queen platform bed with storage drawers",
    "king tufted upholstered headboard",
    "kids twin bunk bed with stairs",
    "memory foam mattress 12 inch queen",
    "cooling gel hybrid mattress king",
    "metal canopy bed frame",
    // storage
    "tall narrow bookcase 6 shelves",
    "mid-century walnut dresser 6 drawers",
    "shoe storage bench entryway",
    "freestanding pantry cabinet kitchen",
    "tv stand for 75 inch screen",
    // rugs
    "8x10 vintage persian style area rug",
    "washable runner rug for hallway",
    "shag rug cream large living room",
    "outdoor patio rug weatherproof",
    "round jute rug 6 ft",
    // lighting
    "modern brass chandelier dining room",
    "arc floor lamp with marble base",
    "industrial pendant light kitchen island",
    "rechargeable cordless table lamp",
    "smart led bulb color changing",
    // decor
    "large round mirror gold frame",
    "wall clock minimalist black",
    "abstract canvas art set of 3",
    "ceramic vase tall white",
    "throw pillow covers boho set of 4",
    "linen curtains blackout 96 inch",
    "scented soy candle vanilla",
    // bedding
    "100 percent cotton sheet set king",
    "down alternative comforter all season",
    "weighted blanket 15 lb queen",
    "duvet cover boho neutral",
    "mattress topper egg crate",
    // bath
    "luxury turkish cotton bath towels",
    "freestanding tub modern slipper",
    "rain shower head with handheld",
    "shower curtain coastal blue",
    "bathroom vanity 36 inch single sink",
    // kitchen / cookware
    "stainless steel kettle whistling",
    "cast iron skillet pre-seasoned 12 inch",
    "non-stick frying pan set ceramic",
    "stand mixer kitchen artisan",
    "espresso machine semi automatic",
    "air fryer 6 quart digital",
    "drip coffee maker programmable",
    "dutch oven enameled 7 qt",
    "knife block set japanese steel",
    "blender high powered smoothie",
    // dining / tableware
    "stoneware dinnerware set service for 8",
    "wine glasses crystal set of 6",
    "flatware set modern matte black",
    "decorative serving platter ceramic",
    // outdoor
    "patio dining set 6 seater wicker",
    "fire pit propane 30 inch",
    "outdoor sectional with cushions",
    "hammock with stand double",
    "garden bench wood for two",
    "umbrella patio offset 10 ft",
    // office
    "standing desk electric adjustable",
    "monitor arm dual gas spring",
    "bookcase ladder leaning oak",
    "filing cabinet 2 drawer locking",
    // kids
    "kids play kitchen wooden",
    "toddler bed with rails low profile",
    "bean bag chair for teens",
    // pets
    "raised dog bed cooling mesh",
    "cat tree tall multi level",
    // appliances
    "compact dishwasher 18 inch portable",
    "wine cooler dual zone 24 bottle",
    "garbage disposal 1 hp continuous feed",
    // seasonal
    "artificial christmas tree 7 ft prelit",
    "pumpkin throw pillow fall",
    // misc
    "luggage set hardside 3 piece",
    "yoga mat thick eco friendly",
    "humidifier cool mist large room",
    "robot vacuum self emptying",
    "tower fan oscillating quiet",
    "space heater small ceramic",
    "air purifier hepa true large room",
    "bidet attachment dual nozzle",
];
